### ISSUE TITLE
Add signature string to `info` attributes

### ISSUE THREAD

**Issue by nvictus** [4dn-dcic/hic2cool#1]
To make detection of HDF5 groups containing Coolers easier, we decided to include an additional top-level attribute to serve as a signature.

```
info['format'] = "HDF5::Cooler"
```

Also, adding something like `info['generated-by'] = 'hic2cool-xxx'` could also be useful metadata.

**Comment by golobor** [comment]
(a) Cooler.info is read-only; the attributes can be modified at the hdf5 level:
h5py.File(path, mode='a').attrs['generated-by'] = 'hic2cool-xxx'
(b) It would also be super useful to pull the name of the genome assembly into to the attribute attrs['genome-assembly']

**Comment by carlvitzthum** [comment]
Great, I appreciate the feedback. I'll add these features.
