### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by lidaof** [4dn-dcic/hic2cool#13]
Hi developer, I am trying to convert a hic file to a cool file but get the following error.
<pre>
$ hic2cool test.hic test.cool
Traceback (most recent call last):
  File "/usr/local/bin/hic2cool", line 11, in <module>
    load_entry_point('hic2cool==0.3.7', 'console_scripts', 'hic2cool')()
  File "/usr/local/lib/python2.7/dist-packages/hic2cool/__main__.py", line 46, in main
    args.normalization, args.exclude_MT, True)
  File "/usr/local/lib/python2.7/dist-packages/hic2cool/hic2cool_utils.py", line 722, in hic2cool_convert
    req, used_chrs, resolutions, masteridx, genome = read_header(infile)
  File "/usr/local/lib/python2.7/dist-packages/hic2cool/hic2cool_utils.py", line 63, in read_header
    magic_string = struct.unpack('<3s', req.read(3))[0]
TypeError: Struct() argument 1 must be string, not unicode
</pre>

**Comment by nvictus** [comment]
This seems to be an issue coming from older minor versions of Python 2.7! See https://github.com/celery/kombu/issues/622.

Two possible compatibility fixes:
* Drop the `unicode_literals` import, and prefix all intended unicode literals with `u`
* Prefix string arguments to `struct.unpack` with `b` to make them byte literals

Of course, @lidaof  for an immediate fix, you can upgrade to the latest Py2.7 or use Py3.

**Comment by lidaof** [comment]
thanks, updated to python 2.7.13 fixed this.

**Comment by carlvitzthum** [comment]
Thanks for finding this issue! In the next release (0.3.8), this issue will be solved through the second solution suggested by @nvictus.
