### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lidaof** [4dn-dcic/hic2cool#14]
Dear developer,

I got another error while trying to convert an hic to a cool file, could you please tell me how to fix this?
<pre>
################
################
hic file header info:
Chromosomes:  [u'All', u'chr1', u'chr2', u'chr3', u'chr4', u'chr5', u'chr6', u'chr7', u'chr8', u'chr9', u'chr10', u'chr11', u'chr12', u'chr13', u'chr14', u'chr15', u'chr16', u'chr17', u'chr18', u'chr19', u'chr20', u'chr21', u'chr22', u'chrX', u'chrY', u'chrM']
Resolutions:  [2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000]
Genome:  hg19
Traceback (most recent call last):
  File "/opt/apps/python2/bin/hic2cool", line 11, in <module>
    sys.exit(main())
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/__main__.py", line 46, in main
    args.normalization, args.exclude_MT, True)
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/hic2cool_utils.py", line 769, in hic2cool_convert
    chr_footer_info, bin_map, count_map)
  File "/opt/apps/python2/lib/python2.7/site-packages/hic2cool/hic2cool_utils.py", line 419, in parse_hic
    normBinX = c1Norm[x]
IndexError: list index out of range
</pre>

**Comment by carlvitzthum** [comment]
@lidaof Sorry for the slow reply. From the error, it would seem there is a bin missing from the input hic file. Is the file you're using publicly available? I would need to test with it to properly diagnose the issue.

Thanks!

**Comment by lidaof** [comment]
I just double checked and these are the files:
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63525/suppl/GSE63525_IMR90_combined.hic.gz
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63525/suppl/GSE63525_IMR90_combined_30.hic.gz
thanks

**Comment by lidaof** [comment]
sorry, these 2 files are for issue #15

**Comment by lidaof** [comment]
for this issue the file is under https://bcm.app.box.com/v/aidenlab/folder/11235404320 with name `IMR90.hic`

**Comment by carlvitzthum** [comment]
Great, I'll look into it! A bunch of development will be going into hic2cool over the next couple weeks, so I hope to address the issues you've brought up as well as memory issues with running big files. Thanks for reporting your issues.

**Comment by carlvitzthum** [comment]
@lidaof Version 0.4.0 is now released, which I confirmed runs on your files (including those referenced in #15 ). Please let me know if you have any further issues. hic2cool will continue to be under active development, so don't forget to check back soon.

**Comment by carlvitzthum** [comment]
@lidaof Just a quick followup- please use newly released version 0.4.1, which addresses another with hic files from older versions of juicer, such as your `IMR90.hic` file.
