### ISSUE TITLE
Pip install error with os/lzma_stub.h

### ISSUE THREAD

**Issue by pkerpedjiev** [4dn-dcic/hic2cool#21]
Just posting this in case others run into this issue. When installing hic2cool with pip I get:

```
    htslib/cram/cram_io.c:63:10: fatal error: 'os/lzma_stub.h' file not found
```

This is easily fixed by install pysam with conda:

```
conda install -c bioconda pysam
```

**Comment by pkerpedjiev-zymergen** [comment]
Another similar error:

```
Configure: error: liblzma development files not found
```

To solve, make sure that `xz-dev` library is installed.
