### ISSUE TITLE
Error in converting .hic to .cool

### ISSUE THREAD

**Issue by rahmas36** [4dn-dcic/hic2cool#39]
Hi, I want to try out this new protocol called Cut-C, which combines Micro-C with Cut and Run to identify protein-centric interactions at high resolution. The authors uploaded .hic files on GEO which I wanted to convert to m.cool to visualize on HiGlass. However, when converting the .hic file to .cool I received this error message: ... This does not appear to be a HiC file; magic string is incorrect.
I cannot load this file on Juicebox. What could be the problem? I attached the link to the file in question.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3587377

I downloaded the ftp link.

Thanks!

**Comment by burakalver** [comment]
Hi. It looks like the people who submitted the data to GEO used a wrong extension. The file looks like a pairs file, and not a hic file. That is why it can't be accepted by juicer or hic2cool. You should be ableo to use cooler to build a cool file. https://cooler.readthedocs.io/en/latest/
