### ISSUE TITLE
juicer hic (fragment level matrix) convert into cooler

### ISSUE THREAD

**Issue by Linhua-Sun** [4dn-dcic/hic2cool#40]
Hi:
I am wondering whether there is a way to convert fragment level contact matrix into cooler format file. The fragment level contact matrix is from juicer .hic format file (https://github.com/aidenlab/juicer/wiki/Pre) including 8 fragment-delimited resolutions are added: 500f, 250f, 100f, 50f, 20f, 5f, 2f, 1f.
Thanks

**Comment by nvictus** [comment]
[Variable length bins](https://cooler.readthedocs.io/en/latest/schema.html#file-flavors) are supported in cooler. If it is not yet available in hic2cool, you can ingest the same kind of "Pre" input data (i.e. pairs) to [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs), or binned data to [cooler load](https://cooler.readthedocs.io/en/latest/cli.html#cooler-load). 

In the case of fragments, the `bins` argument will be a BED file of the restriction fragment segmentation of the genome. You can use [cooler digest](https://cooler.readthedocs.io/en/latest/cli.html#cooler-digest) to make one if you can't get it from the hic file.

That will give you the 1f resolution. Then use [cooler zoomify](https://cooler.readthedocs.io/en/latest/cli.html#cooler-zoomify) to create an mcool including whatever coarser resolutions you like.

**Comment by Linhua-Sun** [comment]
Wow. Thanks!  Great idea.
