### ISSUE TITLE
faster conversion?

### ISSUE THREAD

**Issue by fanc-WU** [4dn-dcic/hic2cool#42]
I'm trying to convert several relatively big .hic files into mcool format. They are around 20G. It took me 18 hours to convert 4.6G. I was wondering if there is a faster way? I didn't see any options to assign multiple threads or increase memory. 

Thank you so much and best regards,
Fan

**Comment by SooLee** [comment]
I don't think a faster option is available currently, but it looks like multiprocessing may be possible. I will see if I can implement something over the long weekend.

**Comment by SooLee** [comment]
hic2cool 0.8.0 has a multiprocessing option now. It is not very efficient though. Would be slightly helpful for large high-resolution matrices.

**Comment by fanc-WU** [comment]
> hic2cool 0.8.0 has a multiprocessing option now. It is not very efficient though. Would be slightly helpful for large high-resolution matrices.

Thank you so much for implementing this! I really appreciate it
