### ISSUE TITLE
Update requirements to allow newer versions

### ISSUE THREAD

**Issue by paulmenzel** [4dn-dcic/hic2cool#46]
Currently, hic2cool prevents the installation of newer Python packages requiring higher versions than the ones listed in the hic2cool requirements.

Is it documented somewhere, why the versions are pinned down?

**Comment by SooLee** [comment]
Sorry for the confusion. The actual dependencies in `setup.py` were not pinned but there was discrepancy between `setup.py` and `requirements.txt`. Now `setup.py` takes dependencies directly from `requirements.txt` (`requirements.txt` updated to match the old `setup.py`).

**Comment by paulmenzel** [comment]
No problem, thank you for the changes in https://github.com/4dn-dcic/hic2cool/pull/47.

Is there a reason, why the `numpy>=1.10.1,<=1.16.3`, and `scipy<=1.2.1`?

**Comment by SooLee** [comment]
I loosened the criteria in branch `dep` - somehow Travis is not working today though it passed the local tests. I will merge & release later.

**Comment by SooLee** [comment]
0.8.2 is released with loosened version for `numpy`, `scipy` and `pandas`

**Comment by paulmenzel** [comment]
Thanks. Closed by https://github.com/4dn-dcic/hic2cool/pull/48.
