### ISSUE TITLE
hic2cool conda version

### ISSUE THREAD

**Issue by joachimwolff** [4dn-dcic/hic2cool#51]
Hi,

Is there any reason why the dependencies on conda are more restricted than in you requirements.txt file?

```
- numpy >=1.10.1,<=1.16.3
    - scipy <=1.2.1
    - pandas <=0.24.2
    - cooler>=0.8.5
    - h5py >=2.8.0
  run:
    - python
    - numpy >=1.10.1,<=1.16.3
    - scipy <=1.2.1
    - pandas <=0.24.2
    - cooler>=0.8.5
    - h5py >=2.8.0
```

Especially the `<=` restrictions are difficult because they prevent the update to new releases which other dependencies are requesting. 

Best,

Joachim

**Comment by SooLee** [comment]
Hmm. Good question. We are not maintaining the conda version actually. I'm guessing that there were problems related to dependency versions. But I'm not sure. Which dependency are you having an issue with?

**Comment by joachimwolff** [comment]
All three ;) 

In my experience numpy and scipy restrictions are not necessary, however, I do understand the one for pandas. 

But: your last commit message for requirements.txt is `numpy scipy pandas version restriction removed`. So I think there used to be these restrictions but the bioconda bot is not removing them and updates only the release.

I can remove these restrictions on bioconda, if you like.

**Comment by SooLee** [comment]
I see. I can remove the `<=` restrictions for numpy and scipy and release a new version. It looks like Bioconda creates a new version automatically for every updates?

**Comment by joachimwolff** [comment]
No need for this, just a new build on bioconda. I request your review already.
https://github.com/bioconda/bioconda-recipes/pull/22132

**Comment by SooLee** [comment]
ok I approved the changes, but I'm not 100% sure whether it would still work. Can you let me know? I will try to loosen the criteria and do tests later.

**Comment by joachimwolff** [comment]
Thanks for approving, I will let you know if sth is not working.
