### ISSUE TITLE
hic2cool command not found on zsh

### ISSUE THREAD

**Issue by rahmas36** [4dn-dcic/hic2cool#54]
Hi, I recently updated my MacOS and now the command line shell switched from bash to zsh. I tried running hic2cool but the command was not found this time, even though previously the command always worked under bash. What should I do?

**Comment by pkerpedjiev** [comment]
Were you using `conda`? How did you previously install it?

Check your `~/.bashrc` file for any PATH exports that may need to be ported over to `~/.zshrc`.

**Comment by Kelly-ST-HRI** [comment]
I use hic2cool with zsh regularly without problems. I recommend to close this issue.

**Comment by clarabakker** [comment]
(stale)
